start =
    expression

expression =
    atom
  / list
    
validchar
    = [0-9a-zA-Z_?!+\-=@#$%^&*/.]

spacedExpression =
    spacing expression:expression
        {return expression;}

atom =
    chars:validchar+
        { return chars.join(""); }

list =
    spacing "(" spacing expr:expression tail:spacedExpression* spacing ")" spacing
        {return [expr].concat(tail);}

spacing = [ \n\t]*
